/**
 * Replayable script to generate documentation screenshots.
 *
 * Usage:
 *   bun run dev                          # start the demo server first
 *   npx playwright test scripts/generate-screenshots.ts
 *
 * Or run directly with Playwright's test runner:
 *   npx playwright test --config=playwright.config.ts scripts/generate-screenshots.ts
 *
 * Screenshots are saved to docs/screenshots/.
 * Manual/diagram screenshots (pdflight-comparison.png, pdflight-glyph-geometry.png)
 * are NOT generated by this script.
 */
import { test } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SCREENSHOTS_DIR = path.resolve(__dirname, '../docs/screenshots');

/** Helper: search + highlight all matches with a given color via the demo UI. */
async function searchAndHighlight(
  page: import('@playwright/test').Page,
  text: string,
  color: string,
) {
  await page.getByTestId('highlight-color').fill(color);
  await page.getByTestId('search-input').fill(text);
  await page.getByTestId('search-btn').click();
  await page.waitForTimeout(300);
  await page.getByTestId('highlight-all').click();
  await page.waitForTimeout(100);
}

/** Helper: search, highlight, export JSON, then return the highlight objects. */
async function searchAndExport(
  page: import('@playwright/test').Page,
  text: string,
  color: string,
): Promise<Array<Record<string, unknown>>> {
  await searchAndHighlight(page, text, color);
  await page.locator('#export-json').click();
  await page.waitForTimeout(100);
  const json = await page.locator('#json-io').inputValue();
  return json ? JSON.parse(json) : [];
}

/** Helper: import a batch of highlights via the demo's JSON import. */
async function importHighlights(
  page: import('@playwright/test').Page,
  highlights: Array<Record<string, unknown>>,
) {
  await page.getByTestId('clear-highlights').click();
  await page.waitForTimeout(100);
  await page.locator('#json-io').fill(JSON.stringify(highlights));
  await page.locator('#import-json').click();
  await page.waitForTimeout(300);
}

/** Helper: hide toolbar for clean screenshots, returns a restore function. */
async function hideToolbar(page: import('@playwright/test').Page) {
  await page.evaluate(() => {
    const tb = document.querySelector('.pdflight-toolbar') as HTMLElement;
    if (tb) tb.style.display = 'none';
  });
  return async () => {
    await page.evaluate(() => {
      const tb = document.querySelector('.pdflight-toolbar') as HTMLElement;
      if (tb) tb.style.display = '';
    });
  };
}

// ---------------------------------------------------------------------------
// Screenshots
// ---------------------------------------------------------------------------

test.describe('Generate documentation screenshots', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('full-page-highlights.png — "Lorem" highlighted across title, subtitle, body', async ({
    page,
  }) => {
    await page.selectOption('[data-testid="demo-pdf-select"]', 'file-sample_150kB.pdf');
    await page.waitForSelector('[data-testid="pdf-viewer"] canvas', { timeout: 10_000 });

    await searchAndHighlight(page, 'Lorem', '#ffff00');

    // Scroll to top
    await page.evaluate(() => {
      document.querySelector('.pdf-viewer')?.scrollTo(0, 0);
    });
    await page.waitForTimeout(200);

    // Screenshot the page container
    const container = page.locator('.pdflight-page-container').first();
    await container.screenshot({
      path: path.join(SCREENSHOTS_DIR, 'full-page-highlights.png'),
    });
  });

  test('zoomed-highlight-accuracy.png — zoomed to 154%, "Lorem" highlighted', async ({
    page,
  }) => {
    await page.selectOption('[data-testid="demo-pdf-select"]', 'file-sample_150kB.pdf');
    await page.waitForSelector('[data-testid="pdf-viewer"] canvas', { timeout: 10_000 });

    // Zoom to ~154%
    const zoomIn = page.locator('.pdflight-toolbar-btn:has-text("+")');
    for (let i = 0; i < 5; i++) {
      await zoomIn.click();
      await page.waitForTimeout(150);
    }

    await searchAndHighlight(page, 'Lorem', '#ffff00');
    await page.evaluate(() => {
      document.querySelector('.pdf-viewer')?.scrollTo(0, 0);
    });
    await page.waitForTimeout(300);

    // Crop to title + subtitle area
    const restore = await hideToolbar(page);
    const container = page.locator('.pdflight-page-container').first();
    const box = await container.boundingBox();
    if (box) {
      await page.screenshot({
        path: path.join(SCREENSHOTS_DIR, 'zoomed-highlight-accuracy.png'),
        clip: { x: box.x, y: box.y, width: box.width, height: Math.min(box.height, 300) },
      });
    }
    await restore();
  });

  test('overlapping-highlights-zoomed.png — "Lorem ips" yellow + "ipsum" blue', async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 1200 });
    await page.selectOption('[data-testid="demo-pdf-select"]', 'file-sample_150kB.pdf');
    await page.waitForSelector('[data-testid="pdf-viewer"] canvas', { timeout: 10_000 });

    // Zoom to 150%
    const zoomIn = page.locator('.pdflight-toolbar-btn:has-text("+")');
    for (let i = 0; i < 4; i++) {
      await zoomIn.click();
      await page.waitForTimeout(150);
    }

    // Build overlapping highlights via export/import
    const allHighlights: Array<Record<string, unknown>> = [];
    let id = 0;

    // "Lorem ips" in yellow
    const yellowHL = await searchAndExport(page, 'Lorem ips', '#ffff00');
    for (const h of yellowHL) {
      h.id = `overlap-${id++}`;
      h.color = '#ffff0080';
    }
    allHighlights.push(...yellowHL);

    // "ipsum" in blue
    const blueHL = await searchAndExport(page, 'ipsum', '#4488ff');
    for (const h of blueHL) {
      h.id = `overlap-${id++}`;
      h.color = '#4488ff80';
    }
    allHighlights.push(...blueHL);

    await importHighlights(page, allHighlights);
    await page.evaluate(() => {
      document.querySelector('.pdf-viewer')?.scrollTo(0, 0);
    });
    await page.waitForTimeout(300);

    // Hide chrome for clean crop
    const restore = await hideToolbar(page);
    await page.evaluate(() => {
      const controls = document.querySelector('.controls-panel') as HTMLElement;
      if (controls) controls.style.display = 'none';
    });
    await page.waitForTimeout(100);

    // Crop to title + subtitle showing overlap
    const container = page.locator('.pdflight-page-container').first();
    const box = await container.boundingBox();
    if (box) {
      await page.screenshot({
        path: path.join(SCREENSHOTS_DIR, 'overlapping-highlights-zoomed.png'),
        clip: { x: box.x, y: box.y, width: box.width, height: Math.min(box.height, 380) },
      });
    }
    await page.evaluate(() => {
      const controls = document.querySelector('.controls-panel') as HTMLElement;
      if (controls) controls.style.display = '';
    });
    await restore();
  });

  test('odio-highlight-accurate.png — italic text block with precise highlights', async ({
    page,
  }) => {
    // Use a tall viewport so all highlights are visible without scrolling
    await page.setViewportSize({ width: 1280, height: 1200 });
    await page.selectOption('[data-testid="demo-pdf-select"]', 'file-sample_150kB.pdf');
    await page.waitForSelector('[data-testid="pdf-viewer"] canvas', { timeout: 10_000 });

    // Zoom to 150%
    const zoomIn = page.locator('.pdflight-toolbar-btn:has-text("+")');
    for (let i = 0; i < 4; i++) {
      await zoomIn.click();
      await page.waitForTimeout(150);
    }

    // Build multi-color highlights via export/import
    const allHighlights: Array<Record<string, unknown>> = [];
    let id = 0;

    const searches = [
      { text: 'Lorem ipsum dolor sit amet, consectetur adipiscing', color: '#ffff0080' },
      { text: 'elit. Nunc ac faucibus odio.', color: '#ffff0080' },
      { text: 'odio', color: '#ff990080' },
      { text: 'Nullam mollis convallis ipsum', color: '#00ccff80' },
    ];

    for (const s of searches) {
      const exported = await searchAndExport(page, s.text, s.color.slice(0, 7));
      for (const h of exported) {
        h.id = `doc-${id++}`;
        h.color = s.color;
      }
      allHighlights.push(...exported);
    }

    await importHighlights(page, allHighlights);
    await page.evaluate(() => {
      document.querySelector('.pdf-viewer')?.scrollTo(0, 0);
    });
    await page.waitForTimeout(300);

    // Hide toolbar and controls for clean crop
    const restore = await hideToolbar(page);
    await page.evaluate(() => {
      const controls = document.querySelector('.controls-panel') as HTMLElement;
      if (controls) controls.style.display = 'none';
    });
    await page.waitForTimeout(200);

    // Find crop bounds from all visible page-1 highlights.
    // Include subtitle but trim generous margins to emphasize the italic text.
    const rects = await page.evaluate(() => {
      const els = document.querySelectorAll('.pdflight-highlight');
      return Array.from(els).map((el) => {
        const r = el.getBoundingClientRect();
        return { top: r.top, bottom: r.bottom };
      });
    });

    const topY = Math.min(...rects.map((r) => r.top));
    const bottomY = Math.max(...rects.map((r) => r.bottom));

    const container = page.locator('.pdflight-page-container').first();
    const box = await container.boundingBox();
    if (box) {
      // Tight vertical crop around highlights; trim page margins on sides
      const margin = 30;
      await page.screenshot({
        path: path.join(SCREENSHOTS_DIR, 'odio-highlight-accurate.png'),
        clip: {
          x: box.x + margin,
          y: topY - 5,
          width: box.width - margin * 2,
          height: bottomY - topY + 10,
        },
      });
    }

    // Restore
    await page.evaluate(() => {
      const controls = document.querySelector('.controls-panel') as HTMLElement;
      if (controls) controls.style.display = '';
    });
    await restore();
  });

  test('rotated-text-highlights.png — word cloud with rotated highlights', async ({ page }) => {
    await page.selectOption('[data-testid="demo-pdf-select"]', 'word-cloud2.pdf');
    await page.waitForSelector('[data-testid="pdf-viewer"] canvas', { timeout: 10_000 });

    // Highlight several words in different colors
    const allHighlights: Array<Record<string, unknown>> = [];
    let id = 0;

    const words = [
      { text: 'Python', color: '#ffff0080' },
      { text: 'LLM', color: '#ff660080' },
      { text: 'TypeScript', color: '#00ccff80' },
      { text: 'Docker', color: '#ff44aa80' },
      { text: 'Rust', color: '#44ff4480' },
      { text: 'AI', color: '#aa88ff80' },
    ];

    for (const w of words) {
      const exported = await searchAndExport(page, w.text, w.color.slice(0, 7));
      for (const h of exported) {
        h.id = `wc-${id++}`;
        h.color = w.color;
      }
      allHighlights.push(...exported);
    }

    await importHighlights(page, allHighlights);
    await page.waitForTimeout(300);

    // Hide toolbar for clean screenshot
    const restore = await hideToolbar(page);
    await page.waitForTimeout(100);

    // Screenshot the full page container (no zoom, no crop)
    const container = page.locator('.pdflight-page-container').first();
    await container.screenshot({
      path: path.join(SCREENSHOTS_DIR, 'rotated-text-highlights.png'),
    });
    await restore();
  });
});
